import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Vips from 'wasm-vips';
import {useEffect, useState} from "react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [url, setUrl] = useState('')
  useEffect(() => {
    Vips({
      // Disable dynamic modules
      dynamicLibraries: [],
      // Workers needs to import the unbundled version of `vips.js`
      mainScriptUrlOrBlob: './vips.js',
      // wasm-vips is served from the public directory
      locateFile: (fileName, scriptDirectory) => fileName,
      preRun:(module) => {
        module.setAutoDeleteLater(!document.referrer.includes('disableAutoDelete'));
        module.setDelayFunction((fn) => {
          globalThis.cleanup = fn;
        });
        const images = [
          'owl.jpg', 'owl.tif', 'owl.webp', 'owl.jxl', 'owl.avif',
          'banana.webp', 'banana.gif',
          'alphachannel.svg', 'transparency_demo.png'
        ];
        for (const image of images)
          module.FS.createPreloadedFile('/', image, '/images/' + image, true, false);

      }
    }).then((vips) => {
      console.log('libvips version:', vips.version());

      // let im = vips.Image.newFromBuffer(Buffer.from([255, 0, 0, 255]));
      let im = vips.Image.newFromFile('owl.jpg');
      im = im.embed(100, 100, 3000, 3000, {
        extend: 'mirror'
      });
      im = im.multiply([1, 2, 1]);
      const mask = vips.Image.newFromArray([
        [-1, -1, -1],
        [-1, 16, -1],
        [-1, -1, -1]
      ], 8.0);

      im = im.conv(mask, {
        precision: 'integer'
      });

      const outBuffer = im.writeToBuffer('.jpg');
      const blob = new Blob( [ outBuffer ] );
      const url = URL.createObjectURL( blob );
      setUrl(url)
      console.log(outBuffer)
    });
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <img src={url} alt=""/>
        {url}
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
